language: ruby
notifications:
  recipients:
    - piro.outsider.reflex@gmail.com
before_install:
  - curl https://gist.githubusercontent.com/ngs/0b5785020afca7701feab717c6a7603a/raw/mecab_install.sh | bash

