language: ruby
notifications:
  recipients:
    - piro.outsider.reflex@gmail.com
before_install:
  - sudo apt-get update -qq
  - uname -a
  # mecab
  - wget --no-check-certificate https://github.com/piroor/tiny-classifier/raw/master/etc/mecab-0.996.tar.gz && tar zxf mecab-0.996.tar.gz
  - pushd mecab-0.996 && ./configure --enable-utf8-only && make && sudo make install && popd
  - sudo ldconfig
  # mecab-ipadic
  - wget --no-check-certificate https://github.com/piroor/tiny-classifier/raw/master/etc/mecab-ipadic-2.7.0-20070801.tar.gz && tar zxf mecab-ipadic-2.7.0-20070801.tar.gz
  - pushd mecab-ipadic-2.7.0-20070801 && ./configure --with-charset=utf8 && make && sudo make install && popd
  - sudo ldconfig
cache: bundler

