name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: sudo apt-get update -qq
    - run: wget --no-check-certificate https://github.com/piroor/tiny-classifier/raw/master/etc/mecab-0.996.tar.gz && tar zxf mecab-0.996.tar.gz
    - run: pushd mecab-0.996 && ./configure --enable-utf8-only && make && sudo make install && popd
    - run: sudo ldconfig
    - run: wget --no-check-certificate https://github.com/piroor/tiny-classifier/raw/master/etc/mecab-ipadic-2.7.0-20070801.tar.gz && tar zxf mecab-ipadic-2.7.0-20070801.tar.gz
    - run: pushd mecab-ipadic-2.7.0-20070801 && ./configure --with-charset=utf8 && make && sudo make install && popd
    - run: sudo ldconfig
    - run: bundle install --path=vendor/
    - run: bundle exec rake test
